version: "3.0"
services:
  ui:
    build: ./uml_designer/ui
    image: ui
    container_name: ui
    ports:
      - "8080:80"

  node:
    container_name: nodeserver
    build: ./uml_designer/server
    ports:
      - "3000:3000"
    hostname: nodeapp
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    image: nodeapp
    command: npm start

  gateway:
    container_name: apigateway
    build: ./apigateway
    ports:
      - "8054:8054"
    hostname: apigateway
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    depends_on:
      - eureka

  eureka:
    container_name: eurekaserver
    build: ./eurekaserver
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
