version: "3.0"
services:
  ui:
    build: ./uml_designer/ui
    image: ui
    container_name: ui
    ports:
      - "8085:80"

  node:
    container_name: designer_server
    build: ./uml_designer/server
    ports:
      - "3000:3000"
    hostname: nodeapp
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    image: nodeapp
    command: npm start
    depends_on:
      - eureka

  gateway:
    container_name: apigateway
    build: ./apigateway
    ports:
      - "8054:8054"
    hostname: apigateway
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    depends_on:
      - eureka

  eureka:
    container_name: eurekaserver
    build: ./eurekaserver
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/

  crud:
    container_name: Spring-Boot-CRUD
    build: ./springBootCRUD
    ports:
      - "8080:8080"
    hostname: Spring-Boot-CRUD
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - EUREKA_HOST=eureka
      - MYSQL_HOST=mysql
    image: authenticationapp
    depends_on:
      - eureka
      - mysql

  auth:
    container_name: authenticationapp
    build: ./authenticationapp
    ports:
      - "8081:8081"
    hostname: authenticationapp
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - EUREKA_HOST=eureka
      - MYSQL_HOST=mysql
    image: authenticationapp
    depends_on:
      - eureka
      - mysql

  mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=groupxyz
      - MYSQL_DATABASE=groupxyzdb
      - MYSQL_USER=groupxyz
      - MYSQL_PASSWORD=groupxyz
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql

  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=.:/uml_designer #optional
    volumes:
      - .:/uml_designer
    ports:
      - 8443:8443
    restart: unless-stopped
