version: "3.0"
services:
  ui:
    build: ./uml_designer/ui
    image: ui
    container_name: ui
    ports:
      - "8080:80"

  node:
    container_name: designer_server
    build: ./uml_designer/server
    ports:
      - "3000:3000"
    hostname: nodeapp
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    image: nodeapp
    command: npm start
    depends_on:
      - eureka

  gateway:
    container_name: apigateway
    build: ./apigateway
    ports:
      - "8054:8054"
    hostname: apigateway
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    depends_on:
      - eureka

  eureka:
    container_name: eurekaserver
    build: ./eurekaserver
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/

  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=.:/uml_designer #optional
    volumes:
      - .:/uml_designer
    ports:
      - 8443:8443
    restart: unless-stopped
